---
# tasks file for http

- name: installing apache web server 
  yum: 
    name: "{{ package_name }}"
    state: latest

- name: start httpd service
  service: 
    name: "{{ package_name }}"
    state: started

- name: hosting web page
  template: 
    src: index.html
    dest: /var/www/html/
  notify: 
  - restart httpd service 

